[package]
name = "local-guard-upload"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
hex.workspace = true
local-guard-core = { path = "../local-guard-core" }
sha2.workspace = true
thiserror.workspace = true
url.workspace = true
