[package]
name = "local-guard-capture"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
local-guard-core = { path = "../local-guard-core" }
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
screenshots = "0.8.10"
