[package]
name = "local-guard-mosaic"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
local-guard-core = { path = "../local-guard-core" }
thiserror.workspace = true
